#!/usr/bin/perl

# Copyright (c) 2010 Todd T. Fries <todd@fries.net>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

use XML::Feed;

my $feed = XML::Feed->parse(URI->new('http://feeds.feedburner.com/myobsaidwhat')) or die XML::Feed->errstr;

print $feed->title, "\n";

my $i = 0;
for my $entry ($feed->entries) {
	printf "%d: title: %s\n",$i,$entry->title;
	printf "%d: link: %s\n",$i,$entry->link;
	printf "%d: content: %s\n",$i,$entry->content;
	printf "%d: summary: %s\n",$i,$entry->summary;
	printf "%d: author: %s\n",$i,$entry->author;
	$i++;
}
